name: Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if DIPLODOC_STORAGE_BUCKET is set"
        run: |
          if [ -z "${{ vars.DIPLODOC_STORAGE_BUCKET }}" ]; then
            echo "::error:: Missing required variable DIPLODOC_STORAGE_BUCKET. Follow https://diplodoc.com/quickstart to configure your project."
            exit 1
          fi

  build:
    needs: check-env
    if: ${{ github.repository != 'diplodoc-platform/documentation-template' }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1

      - name: Build with Diplodoc Action
        uses: diplodoc-platform/docs-build-action@v3
        with:
          revision: "${{ github.sha }}"
          src-root: "./docs"

  upload:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Upload to S3
        uses: diplodoc-platform/docs-upload-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          storage-endpoint: ${{ vars.DIPLODOC_STORAGE_ENDPOINT }}
          storage-region: ${{ vars.DIPLODOC_STORAGE_REGION }}
          storage-bucket: ${{ vars.DIPLODOC_STORAGE_BUCKET }}
          storage-access-key-id: ${{ secrets.DIPLODOC_ACCESS_KEY_ID }}
          storage-secret-access-key: ${{ secrets.DIPLODOC_SECRET_ACCESS_KEY }}

  release:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Release on Diplodoc
        uses: diplodoc-platform/docs-release-action@v2
        with:
          revision: "${{ github.sha }}"
          storage-bucket: ${{ vars.DIPLODOC_STORAGE_BUCKET }}
          storage-access-key-id: ${{ secrets.DIPLODOC_ACCESS_KEY_ID }}
          storage-secret-access-key: ${{ secrets.DIPLODOC_SECRET_ACCESS_KEY }}
          project-link: ${{ vars.DIPLODOC_PROJECT_LINK }}
