name: Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:    
      - main

jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - name: "Check is DIPLODOC_STORAGE_BUCKET secret exists"
        env:
          storage-bucket: ${{ vars.DIPLODOC_STORAGE_BUCKET }}
        if: ${{ env.storage-bucket == '' }}
        run: |
          echo "::error:: The variable \"DIPLODOC_STORAGE_BUCKET\" has not been made; please check that all necessary secrets and variables are installed or follow the link https://diplodoc.com/quickstart"
          exit 1

  build:
    needs: check-env
    if: ${{ github.repository != 'diplodoc-platform/documentation-template' }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20.18.1
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1

      - name: Install Diplodoc CLI
        run: npm install -g @diplodoc/cli@latest

      - name: Build documentation
        run: yfm build ./docs -o ./_docs-build

      - name: Check that _docs-build exists
        run: |
          if [ ! -d "./_docs-build" ]; then
            echo "::error:: Build output folder '_docs-build' not found. Build might have failed."
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-md
          include-hidden-files: true
          path: ./_docs-build
          retention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false

  upload:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Upload to storage
        uses: diplodoc-platform/docs-upload-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          storage-endpoint: ${{ vars.DIPLODOC_STORAGE_ENDPOINT }}
          storage-region: ${{ vars.DIPLODOC_STORAGE_REGION }}
          storage-bucket: ${{ vars.DIPLODOC_STORAGE_BUCKET }}
          storage-access-key-id: ${{ secrets.DIPLODOC_ACCESS_KEY_ID }}
          storage-secret-access-key: ${{ secrets.DIPLODOC_SECRET_ACCESS_KEY }}

  release:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: diplodoc-platform/docs-release-action@v2
        with:
          revision: "${{ github.sha }}"
          storage-bucket: ${{ vars.DIPLODOC_STORAGE_BUCKET }}
          storage-access-key-id: ${{ secrets.DIPLODOC_ACCESS_KEY_ID }}
          storage-secret-access-key: ${{ secrets.DIPLODOC_SECRET_ACCESS_KEY }}
          project-link: ${{ vars.DIPLODOC_PROJECT_LINK }}
